[package]
name = "dispa"
version = "0.1.0"
edition = "2021"
authors = ["iannil <zhurongx@gmail.com>"]
description = "A high-performance traffic interception and forwarding proxy"
license = "MIT"

[dependencies]
tokio = { version = "1.35", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = { version = "0.24", features = ["webpki-roots"] }
rustls = "0.22"
tokio-rustls = "0.25"

# Configuration and CLI
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
config = "0.14"
clap = { version = "4.4", features = ["derive"] }
toml = "0.8"
rustls-pemfile = "2.0"

# Database and storage
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "sqlite", "chrono", "uuid", "tls-rustls"] }

# Logging and monitoring
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
metrics = "0.22"
metrics-exporter-prometheus = "0.12"

# HTTP client for forwarding
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }

# Utilities
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
thiserror = "1.0"
bytes = "1.5"
once_cell = "1.19"
rand = "0.8"
sha2 = "0.10"

# DNS resolution

# File watching for hot-reload
notify = "6.1"
regex = "1.11.2"
url = "2.5.7"

[dev-dependencies]
wiremock = "0.6"
tempfile = "3.8"
