version: '3.8'

services:
  dispa:
    build: .
    container_name: dispa
    restart: unless-stopped
    ports:
      - "8080:8080"    # 代理端口
      - "8081:8081"    # 健康检查端口
      - "9090:9090"    # 监控端口
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dispa-network

  # 可选：添加 Prometheus 监控
  prometheus:
    image: prom/prometheus:latest
    container_name: dispa-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - dispa-network
    depends_on:
      - dispa

  # 可选：添加 Grafana 可视化
  grafana:
    image: grafana/grafana:latest
    container_name: dispa-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - dispa-network
    depends_on:
      - prometheus

volumes:
  grafana-storage:

networks:
  dispa-network:
    driver: bridge