[server]
bind = "0.0.0.0:8081"
workers = 4

[domains]
intercept_domains = ["example.com", "api.example.com", "*.test.com"]
exclude_domains = ["admin.example.com"]
wildcard_support = true

[[targets.targets]]
name = "backend1"
address = "http://192.168.1.100:3000"
url = "http://192.168.1.100:3000"
weight = 3
timeout = 30

[[targets.targets]]
name = "backend2"
address = "http://192.168.1.101:3000"
url = "http://192.168.1.101:3000"
weight = 2
timeout = 30

[[targets.targets]]
name = "backend3"
address = "http://192.168.1.102:3000"
url = "http://192.168.1.102:3000"
weight = 1
timeout = 30

[targets.load_balancing]
algorithm = "Weighted"
lb_type = "Weighted"
sticky_sessions = false

[targets.health_check]
enabled = true
interval = 30
timeout = 10
threshold = 3
healthy_threshold = 2
unhealthy_threshold = 3

[logging]
enabled = true
log_type = "File"
retention_days = 30

# 数据库日志配置 (当type为database或both时使用)
[logging.database]
url = "sqlite://./data/traffic.db"
max_connections = 10
connection_timeout = 30

[logging.file]
directory = "./logs"
max_file_size = 104857600  # 100MB
rotation = true

[monitoring]
enabled = true
bind = "127.0.0.1:8082"
health_endpoint = "/health"
metrics_endpoint = "/metrics"
prometheus_enabled = true
metrics_port = 9091
health_check_port = 8082