[server]
bind_address = "0.0.0.0:8080"
workers = 4
keep_alive_timeout = 60
request_timeout = 30

[domains]
intercept_domains = ["example.com", "api.example.com", "*.test.com"]
exclude_domains = ["admin.example.com"]
wildcard_support = true

[[targets.targets]]
name = "backend1"
url = "http://192.168.1.100:3000"
weight = 3
timeout = 30

[[targets.targets]]
name = "backend2"
url = "http://192.168.1.101:3000"
weight = 2
timeout = 30

[[targets.targets]]
name = "backend3"
url = "http://192.168.1.102:3000"
weight = 1
timeout = 30

[targets.load_balancing]
type = "weighted"
sticky_sessions = false

[targets.health_check]
enabled = true
interval = 30
timeout = 10
healthy_threshold = 2
unhealthy_threshold = 3

[logging]
enabled = true
type = "file"  # file | database | both
retention_days = 30

# 数据库日志配置 (当type为database或both时使用)
[logging.database]
url = "sqlite://./data/traffic.db"
max_connections = 10
connection_timeout = 30

[logging.file]
directory = "./logs"
max_file_size = 104857600  # 100MB
rotation = true

[monitoring]
enabled = true
bind = "0.0.0.0:8081"
health_endpoint = "/health"
metrics_endpoint = "/metrics"
prometheus_enabled = true
metrics_port = 9090
health_check_port = 8081

# 容量监控配置
[monitoring.capacity]
enabled = true

[monitoring.capacity.memory]
enabled = true
warning_threshold = 0.8    # 80% 内存使用警告阈值
critical_threshold = 0.95  # 95% 内存使用临界阈值
check_interval = 30        # 检查间隔(秒)

[monitoring.capacity.connections]
enabled = true
max_per_target = 1000      # 每个目标的最大连接数
global_max = 5000          # 全局最大连接数
warning_threshold = 0.8    # 80% 连接数警告阈值

[monitoring.capacity.request_rate]
enabled = true
max_rps = 10000           # 最大每秒请求数
window_size = 60          # 统计窗口(秒)
warning_threshold = 0.8   # 80% RPS警告阈值

# HTTP客户端配置
[http_client]
pool_max_idle_per_host = 32
pool_idle_timeout = 300
connect_timeout = 10
request_timeout = 60
user_agent = "Dispa/0.1.0"

# 缓存配置 (可选)
[cache]
enabled = false
max_size = 104857600  # 100MB
default_ttl = 3600    # 1小时
etag_enabled = true
metrics_enabled = true
key_prefix = "dispa"

# 安全配置 (可选)
[security]
enabled = false

# TLS配置 (可选)
[tls]
enabled = false
port = 8443

# 路由配置 (可选)
[routing]
enabled = false
enable_logging = false

# 插件配置 (可选)
[plugins]
enabled = false
max_concurrency = 10
timeout = 30